<html>
    <div class="page">
        <div style="min-width:630px;">
            <div style="font-size: 26px; font-family:Arial; font-weight:bold; color:#014a8c;  ">
                Zoekt u contact?
            </div>
        </div>
        <br/>
        <p><?php echo $salutation; ?>  <strong><?php echo $email_to_name; ?></strong></p>
        <p>Wij hebben uw contact formulier in goede orde ontvangen!</p>
        <p>
            Onderwerp: <?php echo $subject; ?><br/>
            Bericht:<br/>
            <?php echo $message; ?>
        </p>
        <p>Mocht u toch nog vragen hebben neem dan contact op met ons: <a href="mailto:sander@verzeilberg.nl">sander@verzeilberg.nl</a></p>
        <p>Groetjes,<br/><br/>Sander</p>
    </div>
</html>
