<div class="form-group <?php echo (count($form->getMessages('fileUpload')) > 0 ? 'has-error' : '' ) ?>">
    <div class="col-sm-6 col-md-6 col-lg-6">
        <?php echo $this->formLabel($form->get('fileUpload')); ?>
        <div class="has-feedback">
                <div class="input-group">
                    <label class="input-group-addon btn btn-file">
                        Browse&hellip; <input type="file" name="fileUpload" style="display: none;" multiple>
                    </label>
                    <input type="text" class="form-control" name="fileUploadFileName" readonly>
                </div>
            </div>
    </div>
</div>
<div class="form-group <?php echo (count($form->getMessages('fileDescription')) > 0 ? 'has-error' : '' ) ?>">
    <div class="col-sm-6 col-md-6 col-lg-6">
        <?php echo $this->formLabel($form->get('fileDescription')); ?>
        <?php echo $this->formText($form->get('fileDescription')); ?>
    </div>
</div>